#!/usr/bin/env python3
"""
VoiceBridge — Weekly Automated Test & Email Reporter
Runs the complete extension test suite and sends an email report to agitner@gmail.com
if any regressions, failures, or syntax issues are detected.
"""

import os
import sys
import subprocess
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime

RECIPIENT_EMAIL = "agitner@gmail.com"
PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RUN_TESTS_SCRIPT = os.path.join(PROJECT_DIR, "run_tests.py")

def run_test_suite():
    """Runs the VoiceBridge test suite and returns (success: bool, output: str)"""
    try:
        proc = subprocess.run(
            [sys.executable, RUN_TESTS_SCRIPT],
            cwd=PROJECT_DIR,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            timeout=60
        )
        return proc.returncode == 0, proc.stdout
    except Exception as e:
        return False, f"Failed to execute test runner: {str(e)}"

def send_email_alert(recipient, success, test_output):
    """Sends an email notification via SMTP or logs report"""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    status_str = "PASSED ✅" if success else "FAILED ❌"
    subject = f"[{status_str}] VoiceBridge Weekly Test Health Report ({timestamp})"

    body = f"""VoiceBridge Weekly Automated Health Check
==================================================
Timestamp: {timestamp}
Status: {status_str}
Recipient: {recipient}

Test Output:
--------------------------------------------------
{test_output}

--------------------------------------------------
This is an automated report generated by VoiceBridge Test Suite.
"""

    smtp_user = os.environ.get("SMTP_USER")
    smtp_pass = os.environ.get("SMTP_PASS")
    smtp_host = os.environ.get("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("SMTP_PORT", "465"))

    if not smtp_user or not smtp_pass:
        print("\n" + "=" * 60)
        print(f"📧 EMAIL REPORT READY (Configure SMTP_USER and SMTP_PASS to send via SMTP)")
        print(f"To: {recipient}")
        print(f"Subject: {subject}")
        print("=" * 60)
        print(body)
        print("=" * 60)
        return

    try:
        msg = MIMEMultipart()
        msg["From"] = f"VoiceBridge Test Reporter <{smtp_user}>"
        msg["To"] = recipient
        msg["Subject"] = subject
        msg.attach(MIMEText(body, "plain"))

        with smtplib.SMTP_SSL(smtp_host, smtp_port) as server:
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_user, recipient, msg.as_string())
        print(f"✅ Alert email successfully sent to {recipient}")
    except Exception as e:
        print(f"⚠️ Could not send email via SMTP: {e}", file=sys.stderr)

def main():
    print(f"🔍 Starting VoiceBridge Weekly Health Check at {datetime.now()}...")
    success, output = run_test_suite()
    print(output)

    # If test failed or if always-reporting is requested, generate email report
    send_email_alert(RECIPIENT_EMAIL, success, output)

    if not success:
        sys.exit(1)
    else:
        print("🎉 Health check completed successfully.")
        sys.exit(0)

if __name__ == "__main__":
    main()
